# Generated by Django 4.2.1 on 2023-05-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_slogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slogo',
            old_name='sanskarsetlogo',
            new_name='sanImage',
        ),
    ]
