# Generated by Django 4.2.1 on 2023-05-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_sanskarsetlogo_slogo_sanimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=256)),
                ('actImage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='slogo',
            name='sanImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
