# Generated by Django 4.2.1 on 2023-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_activities_alter_slogo_sanimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workTitle', models.CharField(max_length=256)),
                ('workImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
