# Generated by Django 4.2.1 on 2023-05-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
    ]
