# Generated by Django 4.2.1 on 2023-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fLogo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
