# Generated by Django 4.2.1 on 2023-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_faqlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=256)),
                ('telephoneNo', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('emailId', models.EmailField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('addressM', models.TextField(max_length=256)),
            ],
        ),
    ]
