# Generated by Django 4.2.1 on 2023-05-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='addressM',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='emailId',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='telephoneNo',
        ),
    ]
