# Generated by Django 4.2.1 on 2023-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_contactus_addressm_remove_contactus_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
