# Generated by Django 4.2.1 on 2023-05-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_contactus_address_alter_contactus_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=15)),
                ('subMenu', models.CharField(max_length=256)),
                ('urlMenu', models.CharField(max_length=256)),
            ],
        ),
    ]
