# Generated by Django 4.2.1 on 2023-05-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='subMenu',
        ),
    ]
