# Generated by Django 4.2.1 on 2023-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_menu_submenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='urlMenu',
            new_name='URL',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menuName',
            field=models.CharField(max_length=256),
        ),
    ]
