# Generated by Django 4.2.1 on 2023-05-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_rename_urlmenu_menu_url_alter_menu_menuname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='URL',
            new_name='url',
        ),
    ]
