# Generated by Django 4.2.1 on 2023-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_rename_url_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenuName', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
    ]
