# Generated by Django 4.2.1 on 2023-05-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='submenuName',
        ),
        migrations.AddField(
            model_name='submenu',
            name='subMenuName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='submenu', to='application.menu'),
        ),
    ]
