# Generated by Django 4.2.1 on 2023-05-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_remove_submenu_submenuname_submenu_submenuname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='subMenuName',
        ),
        migrations.AddField(
            model_name='submenu',
            name='menu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='application.menu'),
        ),
        migrations.AddField(
            model_name='submenu',
            name='subMenu',
            field=models.CharField(default='', max_length=256),
        ),
    ]
