# Generated by Django 4.2.1 on 2023-05-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_remove_submenu_submenu_submenu_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='submenu',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
