# Generated by Django 4.2.1 on 2023-05-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_alter_submenu_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='introduction',
        ),
    ]
