# Generated by Django 4.2.1 on 2023-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_remove_introduction_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='introduction',
            field=models.CharField(default='', max_length=256),
        ),
    ]
