# Generated by Django 4.2.1 on 2023-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_alter_introduction_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='introduction',
            field=models.TextField(),
        ),
    ]
