# Generated by Django 4.2.1 on 2023-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_alter_introduction_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setLogo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
