# Generated by Django 4.2.1 on 2023-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_setlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDhamLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhaLogo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
