# Generated by Django 4.2.1 on 2023-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_sdhamlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopHeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
