# Generated by Django 4.2.1 on 2023-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_topheadertext'),
    ]

    operations = [
        migrations.AddField(
            model_name='topheadertext',
            name='tlLogo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
