# Generated by Django 4.2.1 on 2023-06-01 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftBackGroundAndText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textLine', ckeditor.fields.RichTextField()),
                ('backgroundImage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
