# Generated by Django 4.2.1 on 2023-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_leftbackgroundandtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightBannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
