# Generated by Django 4.2.1 on 2023-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftSideTopBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='LeftBackGroundAndText',
        ),
    ]
