# Generated by Django 4.2.1 on 2023-06-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_leftsidetopbackground_delete_leftbackgroundandtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='actImage',
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='application.activities')),
            ],
        ),
    ]
