# Generated by Django 4.2.1 on 2023-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_remove_activities_actimage_activityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='largeImage1',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='activities',
            name='smallImage1',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='activities',
            name='smallImage2',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='activities',
            name='smallImage3',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='activities',
            name='smallImage4',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
    ]
