# Generated by Django 4.2.1 on 2023-06-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_rename_largeimage1_activities_largeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('timage', models.ImageField(default='', upload_to='images')),
                ('designation', models.CharField(max_length=256)),
                ('remark', models.CharField(default='', max_length=256)),
                ('teamName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.ourteam')),
            ],
        ),
    ]
