# Generated by Django 4.2.1 on 2023-06-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_alter_job_teamname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='teamName',
            new_name='jobname',
        ),
    ]
