# Generated by Django 4.2.1 on 2023-06-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_rename_teamname_job_jobname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proLogo', models.ImageField(default='', upload_to='images')),
                ('productName', models.CharField(max_length=256)),
                ('rs', models.CharField(max_length=256)),
            ],
        ),
    ]
